# Generated by Django 5.1.1 on 2025-02-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApp', '0002_remove_dishes_description_remove_dishes_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='image',
            field=models.ImageField(null=True, upload_to='dishes/'),
        ),
    ]
