# Generated by Django 5.1.1 on 2025-02-19 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApp', '0004_remove_cart_dish_remove_cart_quantity_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cafeApp.dishes'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Cart_item',
        ),
    ]
