# Generated by Django 5.1.1 on 2025-03-24 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApp', '0005_cart_dish_cart_quantity_delete_cart_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="Повне ім'я")),
                ('address', models.TextField(verbose_name='Адреса')),
                ('credit_card', models.CharField(max_length=16, verbose_name='Кредитна карта')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('processing', 'Обробляється'), ('delivered', 'Доставлено'), ('canceled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
