# Generated by Django 5.1.1 on 2025-03-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApp', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carts',
            field=models.ManyToManyField(to='cafeApp.cart', verbose_name='Страви у замовленні'),
        ),
    ]
