# Generated by Django 5.1.1 on 2025-03-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApp', '0008_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='category',
            field=models.CharField(choices=[('garnish', 'Гарніри'), ('dessert', 'Десерти'), ('drinks', 'Напої')], default='garnish', max_length=20),
        ),
    ]
